# Generated by Django 6.1.1 on 2026-10-06 06:19

from django.db import migrations, models


def seed_slides(apps, schema_editor):
    """Start the slider with the photos already on the home page: the current
    banner photo, then the other home photos from the gallery (if present).
    Slides point at the existing files; nothing is copied."""
    HeroSection = apps.get_model("website", "HeroSection")
    HeroSlide = apps.get_model("website", "HeroSlide")
    GalleryImage = apps.get_model("website", "GalleryImage")
    if HeroSlide.objects.exists():
        return

    files = []
    hero = HeroSection.objects.filter(pk=1).first()
    if hero and hero.background_image:
        files.append((hero.background_image.name,
                      "A church congregation gathered outside the church building"))
    extra = [
        ("home-2.jpeg", "Church members standing together at the church entrance"),
        ("home-3.jpeg", "A teacher leading a Bible class"),
        ("home-4.jpeg", "A baptism in water"),
    ]
    for filename, alt in extra:
        img = GalleryImage.objects.filter(image__endswith=filename).first()
        if img and img.image:
            files.append((img.image.name, alt))

    for order, (name, alt) in enumerate(files, start=1):
        HeroSlide.objects.create(image=name, alt_text=alt, order=order, is_active=True)


def grant_content_manager(apps, schema_editor):
    """Give the Content Manager role the new Banner slides permissions
    (same as running `manage.py setup_roles` again)."""
    from django.contrib.auth.management import create_permissions
    app_config = apps.get_app_config("website")
    app_config.models_module = True  # migration-state configs are skipped otherwise
    create_permissions(app_config, apps=apps, verbosity=0)
    app_config.models_module = None
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    group = Group.objects.filter(name="Content Manager").first()
    if group:
        group.permissions.add(*Permission.objects.filter(
            content_type__app_label="website", content_type__model="heroslide"))


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="home/slides/")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="A few words describing the photo, for visitors using screen readers.",
                        max_length=200,
                        verbose_name="Photo description",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Banner slide",
                "verbose_name_plural": "Banner slides",
                "ordering": ["order", "id"],
            },
        ),
        migrations.RunPython(seed_slides, migrations.RunPython.noop),
        migrations.RunPython(grant_content_manager, migrations.RunPython.noop),
    ]
