# Generated by Django 6.1.1 on 2026-10-07 10:29

import django.core.validators
import django.db.models.deletion
import website.models
from django.db import migrations, models


PAGES = ["home", "about", "ministry_list", "bible_school", "event_list",
         "gallery", "blog_list", "contact", "church_list"]


def create_page_rows(apps, schema_editor):
    """One SEO row per main page, so every page is listed in the CMS ready to edit."""
    PageSEO = apps.get_model("website", "PageSEO")
    for key in PAGES:
        PageSEO.objects.get_or_create(page=key)


def grant_roles(apps, schema_editor):
    """Give the existing roles access to the new screens
    (same result as running `manage.py setup_roles` again)."""
    from django.contrib.auth.management import create_permissions
    app_config = apps.get_app_config("website")
    app_config.models_module = True  # migration-state configs are skipped otherwise
    create_permissions(app_config, apps=apps, verbosity=0)
    app_config.models_module = None

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    def perms(model, actions=("add", "change", "delete", "view")):
        return Permission.objects.filter(
            content_type__app_label="website", content_type__model=model,
            codename__in=[f"{a}_{model}" for a in actions])

    manager = Group.objects.filter(name="Content Manager").first()
    if manager:
        for model in ("galleryvideo", "pageseo", "newslettersubscriber", "prayerlistsignup"):
            manager.permissions.add(*perms(model))
    editor = Group.objects.filter(name="Editor").first()
    if editor:
        editor.permissions.add(*perms("galleryvideo", ("add", "change", "view")))
        editor.permissions.add(*perms("newslettersubscriber", ("view",)))
        editor.permissions.add(*perms("prayerlistsignup", ("view",)))


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_heroslide"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageSEO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("about", "About"),
                            ("ministry_list", "Ministries"),
                            ("bible_school", "ICTC"),
                            ("event_list", "Events"),
                            ("gallery", "Gallery"),
                            ("blog_list", "Blog"),
                            ("contact", "Contact"),
                            ("church_list", "Churches"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="The title shown in the browser tab and on Google. About 50–60 characters is best. Leave empty to use the normal page title.",
                        max_length=70,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="The short text under the title on Google. About 150 characters is best.",
                        max_length=160,
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Optional. A few words separated by commas, e.g. church of Christ, Punjab, Kerala.",
                        max_length=255,
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        help_text="Title shown when this page is shared on WhatsApp, Facebook or X. Leave empty to use the meta title.",
                        max_length=95,
                        verbose_name="Share title",
                    ),
                ),
                (
                    "og_description",
                    models.CharField(
                        blank=True,
                        help_text="Text shown when this page is shared. Leave empty to use the meta description.",
                        max_length=200,
                        verbose_name="Share description",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Picture shown when this page is shared. Best size 1200 × 630 pixels. Leave empty to use the default share image from Website Settings.",
                        null=True,
                        upload_to="seo/",
                        verbose_name="Share image",
                    ),
                ),
                (
                    "noindex",
                    models.BooleanField(
                        default=False,
                        help_text="Tick only if this page should not appear in Google search results.",
                        verbose_name="Hide from Google",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page SEO",
                "verbose_name_plural": "Page SEO",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="galleryalbum",
            name="seo_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="galleryalbum",
            name="seo_image",
            field=models.ImageField(blank=True, null=True, upload_to="seo/"),
        ),
        migrations.AddField(
            model_name="galleryalbum",
            name="seo_title",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_seo_keywords",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="google_site_verification",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="GalleryVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True,
                        help_text="Paste the link from YouTube (Share → Copy link). Leave empty if you upload a video file below.",
                        verbose_name="YouTube link",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="MP4 works on every phone and browser. Leave empty if you pasted a YouTube link.",
                        null=True,
                        upload_to="gallery/videos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp4", "webm", "mov", "m4v"]
                            ),
                            website.models.validate_video_size,
                        ],
                        verbose_name="Video file",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Optional. Shown before the video plays. YouTube videos use YouTube's own picture if this is empty.",
                        null=True,
                        upload_to="gallery/videos/covers/",
                        verbose_name="Cover photo",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="website.galleryalbum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery video",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.RunPython(create_page_rows, migrations.RunPython.noop),
        migrations.RunPython(grant_roles, migrations.RunPython.noop),
    ]
