import datetime

from django.test import TestCase
from django.utils import timezone

from website import models as m


class ChurchModelTests(TestCase):
    def test_slug_autogenerated(self):
        church = m.Church.objects.create(name="Kottayam Church of Christ", region="kerala")
        self.assertEqual(church.slug, "kottayam-church-of-christ")

    def test_slug_unique_on_duplicate_name(self):
        m.Church.objects.create(name="Grace Church", region="kerala")
        second = m.Church.objects.create(name="Grace Church", region="kerala")
        self.assertEqual(second.slug, "grace-church-2")

    def test_get_absolute_url(self):
        church = m.Church.objects.create(name="Test Church", region="kerala")
        self.assertEqual(church.get_absolute_url(), f"/churches/{church.slug}/")

    def test_church_image_relationship(self):
        church = m.Church.objects.create(name="Gallery Church", region="kerala")
        m.ChurchImage.objects.create(church=church, image="churches/gallery/test.jpg")
        self.assertEqual(church.gallery.count(), 1)


class EventModelTests(TestCase):
    def test_is_upcoming_and_is_past(self):
        today = timezone.localdate()
        future_event = m.Event.objects.create(name="Future Event", start_date=today + datetime.timedelta(days=5))
        past_event = m.Event.objects.create(name="Past Event", start_date=today - datetime.timedelta(days=5))
        self.assertTrue(future_event.is_upcoming)
        self.assertFalse(future_event.is_past)
        self.assertTrue(past_event.is_past)
        self.assertFalse(past_event.is_upcoming)

    def test_completed_flag_forces_past(self):
        today = timezone.localdate()
        event = m.Event.objects.create(
            name="Marked Complete", start_date=today + datetime.timedelta(days=5), is_completed=True,
        )
        self.assertTrue(event.is_past)
        self.assertFalse(event.is_upcoming)


class BlogPostModelTests(TestCase):
    def test_slug_and_display_author(self):
        post = m.BlogPost.objects.create(title="A Field Report", content="<p>Body</p>", author_name="Office")
        self.assertEqual(post.slug, "a-field-report")
        self.assertEqual(post.display_author, "Office")

    def test_tags_relationship(self):
        post = m.BlogPost.objects.create(title="Tagged Post", content="<p>Body</p>")
        tag = m.BlogTag.objects.create(name="Kerala")
        post.tags.add(tag)
        self.assertEqual(post.tags.count(), 1)
        self.assertEqual(tag.posts.count(), 1)


class SingletonModelTests(TestCase):
    def test_site_settings_is_singleton(self):
        first = m.SiteSettings.load()
        first.site_name = "Updated Name"
        first.save()
        second = m.SiteSettings.load()
        self.assertEqual(first.pk, second.pk)
        self.assertEqual(second.site_name, "Updated Name")
        self.assertEqual(m.SiteSettings.objects.count(), 1)

    def test_hero_section_is_singleton(self):
        first = m.HeroSection.load()
        first.heading = "Updated heading"
        first.save()
        second = m.HeroSection.load()
        self.assertEqual(second.heading, "Updated heading")
        self.assertEqual(m.HeroSection.objects.count(), 1)


class GalleryAlbumModelTests(TestCase):
    def test_album_slug_and_images(self):
        album = m.GalleryAlbum.objects.create(title="Youth Camp 2026")
        m.GalleryImage.objects.create(album=album, image="gallery/test.jpg")
        self.assertEqual(album.slug, "youth-camp-2026")
        self.assertEqual(album.images.count(), 1)
